In [2]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
titanic_train = pd.read_csv(r"C:\Users\kotar\Desktop\Amar\python\titanic_sample_100.csv")  
titanic_train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Theresa Davis,male,37.0,2,1,39256,75.88,B20,Q
1,2,0,3,Jose Clark,male,28.1,3,0,13905,63.88,E46,S
2,3,0,3,Laura Mccarthy PhD,male,26.7,1,5,95181,15.23,G6,S
3,4,1,1,Phillip Merritt,female,26.7,1,5,65392,87.96,F2,C
4,5,0,2,Tina Mercado,male,52.1,0,0,59797,11.85,E46,C
...,...,...,...,...,...,...,...,...,...,...,...,...
145,146,1,3,Sylvia Skinner,male,28.4,5,5,99241,96.64,B20,Q
146,147,0,2,Jimmy Hernandez,male,37.1,3,0,85965,46.81,F2,Q
147,148,0,2,Stephanie Scott,male,42.1,2,5,64460,25.60,B20,S
148,149,1,3,Jennifer Ortega,male,23.4,4,2,31567,59.43,A10,C
149,150,1,1,Joseph Johnson,female,20.9,3,0,28449,74.31,D33,Q

In [4]:
titanic_train.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,Theresa Davis,male,37.0,2,1,39256,75.88,B20,Q
1,2,0,3,Jose Clark,male,28.1,3,0,13905,63.88,E46,S
2,3,0,3,Laura Mccarthy PhD,male,26.7,1,5,95181,15.23,G6,S
3,4,1,1,Phillip Merritt,female,26.7,1,5,65392,87.96,F2,C
4,5,0,2,Tina Mercado,male,52.1,0,0,59797,11.85,E46,C
5,6,1,1,Dale Finley,female,40.7,5,3,80284,97.29,E46,C
6,7,1,3,Savannah Schmidt,male,23.4,4,2,85674,26.36,D33,Q
7,8,0,3,Lisa Acosta,male,37.6,1,2,20458,26.51,D33,S
8,9,1,2,Lisa Tucker,female,33.4,5,2,31319,48.88,F2,C
9,10,1,3,Cody Cox,male,3.2,5,5,19358,36.21,B20,Q

In [5]:
titanic_train.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
140,141,1,2,Michael Mccormick,male,30.6,5,4,30706,58.66,E46,C
141,142,1,3,Gregory Collins,female,20.9,3,5,42780,67.37,NaN,C
142,143,1,2,Samantha Ellis,male,1.6,0,1,59986,81.57,F2,Q
143,144,1,1,Laurie Rice,female,32.6,5,3,45976,34.37,C123,Q
144,145,1,2,Ronald Davis,male,18.9,1,4,56179,12.28,D33,Q
145,146,1,3,Sylvia Skinner,male,28.4,5,5,99241,96.64,B20,Q
146,147,0,2,Jimmy Hernandez,male,37.1,3,0,85965,46.81,F2,Q
147,148,0,2,Stephanie Scott,male,42.1,2,5,64460,25.60,B20,S
148,149,1,3,Jennifer Ortega,male,23.4,4,2,31567,59.43,A10,C
149,150,1,1,Joseph Johnson,female,20.9,3,0,28449,74.31,D33,Q

In [7]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket           int64
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [8]:
titanic_train.dtypes == "object"

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [6]:

a = titanic_train.dtypes[titanic_train.dtypes == "object"].index
a

Index(['Name', 'Sex', 'Cabin', 'Embarked'], dtype='object')

In [11]:
titanic_train.dtypes[titanic_train.dtypes == "object"]

Name        object
Sex         object
Cabin       object
Embarked    object
dtype: object

In [29]:
titanic_train[a].describe()

                 Name     Sex Cabin Embarked
count             150     150   129      150
unique            150       2     7        3
top     Theresa Davis  female   D33        Q
freq                1      76    24       54

In [12]:
titanic_train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Ticket,Fare
count,150.000000,150.000000,150.000000,150.000000,150.000000,150.00000,150.000000,150.000000
mean,75.500000,0.520000,1.980000,30.395333,2.766667,2.60000,55969.200000,55.512800
std,43.445368,0.501274,0.831187,12.673136,1.781398,1.69484,26109.146486,27.095997
min,1.000000,0.000000,1.000000,1.600000,0.000000,0.00000,10221.000000,10.460000
25%,38.250000,0.000000,1.000000,21.725000,1.000000,1.00000,35046.000000,33.995000
50%,75.500000,1.000000,2.000000,30.700000,3.000000,3.00000,59619.000000,56.905000
75%,112.750000,1.000000,3.000000,37.275000,4.000000,4.00000,78436.000000,80.082500
max,150.000000,1.000000,3.000000,83.900000,5.000000,5.00000,99539.000000,99.100000

In [17]:
titanic_train[['Name','Sex','Age']]

                   Name     Sex   Age
0         Theresa Davis    male  37.0
1            Jose Clark    male  28.1
2    Laura Mccarthy PhD    male  26.7
3       Phillip Merritt  female  26.7
4          Tina Mercado    male  52.1
..                  ...     ...   ...
145      Sylvia Skinner    male  28.4
146     Jimmy Hernandez    male  37.1
147     Stephanie Scott    male  42.1
148     Jennifer Ortega    male  23.4
149      Joseph Johnson  female  20.9

[150 rows x 3 columns]

In [12]:
sorted(titanic_train["Name"])[5:30:2]

['Alexis Lawrence',
 'Amanda Howell',
 'Anna Johnson',
 'Bradley Christensen',
 'Brian Wilson',
 'Carly Harrington',
 'Casey Brennan',
 'Cheryl Berry',
 'Christina Adams',
 'Christopher Bell',
 'Christopher Brown',
 'Clinton Adkins',
 'Dale Finley']

In [22]:
titanic_train["Name"].describe()

count               150
unique              150
top       Theresa Davis
freq                  1
Name: Name, dtype: object

In [7]:
titanic_train[["Ticket"]][4:9:2]

   Ticket
4   59797
6   85674
8   31319

In [25]:
titanic_train["Ticket"].describe()

count      150.000000
mean     55969.200000
std      26109.146486
min      10221.000000
25%      35046.000000
50%      59619.000000
75%      78436.000000
max      99539.000000
Name: Ticket, dtype: float64

In [26]:
titanic_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [30]:
titanic_train["sudh"]="sdffs"
titanic_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,sudh
0,1,0,3,Theresa Davis,male,37.0,2,1,39256,75.88,B20,Q,sdffs
1,2,0,3,Jose Clark,male,28.1,3,0,13905,63.88,E46,S,sdffs
2,3,0,3,Laura Mccarthy PhD,male,26.7,1,5,95181,15.23,G6,S,sdffs
3,4,1,1,Phillip Merritt,female,26.7,1,5,65392,87.96,F2,C,sdffs
4,5,0,2,Tina Mercado,male,52.1,0,0,59797,11.85,E46,C,sdffs

In [31]:
titanic_train["Cabin"][0:15]       # Check the first 15 tickets

0     B20
1     E46
2      G6
3      F2
4     E46
5     E46
6     D33
7     D33
8      F2
9     B20
10    D33
11    A10
12    NaN
13    A10
14    NaN
Name: Cabin, dtype: object

In [32]:
titanic_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket           int64
Fare           float64
Cabin           object
Embarked        object
sudh            object
dtype: object

In [33]:
titanic_train["Survived"]

0      0
1      0
2      0
3      1
4      0
      ..
145    1
146    0
147    0
148    1
149    1
Name: Survived, Length: 150, dtype: int64

In [8]:
new_Pclass = pd.Categorical(titanic_train["Pclass"])

new_Pclass

[3, 3, 3, 1, 2, ..., 3, 2, 2, 3, 1]
Length: 150
Categories (3, int64): [1, 2, 3]

In [38]:
titanic_train["Cabin"].unique()   # Check unique cabins

array(['B20', 'E46', 'G6', 'F2', 'D33', 'A10', nan, 'C123'], dtype=object)

In [9]:
import numpy as np 
char_cabin = titanic_train["Cabin"].astype(str) # Convert data to str

new_Cabin = [cabin[0] for cabin in char_cabin] # Take first letter

new_Cabin = pd.Categorical(new_Cabin)
#new_Cabin
new_Cabin

['B', 'E', 'G', 'F', 'E', ..., 'B', 'F', 'B', 'A', 'D']
Length: 150
Categories (8, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'n']

In [40]:
titanic_train["Cabin"] = new_Cabin
titanic_train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,sudh
0,1,0,3,Theresa Davis,male,37.0,2,1,39256,75.88,B,Q,sdffs
1,2,0,3,Jose Clark,male,28.1,3,0,13905,63.88,E,S,sdffs
2,3,0,3,Laura Mccarthy PhD,male,26.7,1,5,95181,15.23,G,S,sdffs
3,4,1,1,Phillip Merritt,female,26.7,1,5,65392,87.96,F,C,sdffs
4,5,0,2,Tina Mercado,male,52.1,0,0,59797,11.85,E,C,sdffs

In [41]:
titanic_train["Age"].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Name: Age, Length: 150, dtype: bool

In [42]:
missing = np.where(titanic_train["Age"].isnull() == True)
missing

(array([], dtype=int64),)

In [46]:
len(missing[0])

0

In [43]:
np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))

(array([121], dtype=int64),)

In [44]:
titanic_train.iloc[np.where(titanic_train["Fare"]==max(titanic_train["Fare"]))]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,sudh
121,122,0,1,Maria Stewart,female,32.2,2,4,27172,99.1,A,C,sdffs

In [10]:
titanic_train["Family"] = titanic_train["SibSp"] + titanic_train["Parch"]
titanic_train["Family"]

0       3
1       3
2       6
3       6
4       0
       ..
145    10
146     3
147     7
148     6
149     3
Name: Family, Length: 150, dtype: int64

In [11]:
most_family = np.where(titanic_train["Family"] == max(titanic_train["Family"]))
most_family

(array([  9,  26,  39,  76,  86, 104, 130, 135, 145], dtype=int64),)

In [12]:

titanic_train.iloc[most_family]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family
9,10,1,3,Cody Cox,male,3.2,5,5,19358,36.21,B20,Q,10
26,27,0,1,Tammy Marsh,male,28.4,5,5,17716,44.98,D33,S,10
39,40,1,1,Kari Johnson,female,27.4,5,5,51180,39.27,D33,C,10
76,77,1,3,Laura Lawrence,female,16.1,5,5,81582,13.67,D33,C,10
86,87,0,3,Pamela Mayo,male,7.5,5,5,41830,18.38,E46,Q,10
104,105,0,3,Jessica Wagner,female,28.9,5,5,17026,90.28,B20,S,10
130,131,1,2,Richard Schultz,female,43.4,5,5,29936,90.10,NaN,S,10
135,136,1,1,Alex Acevedo,male,3.9,5,5,23173,63.17,NaN,S,10
145,146,1,3,Sylvia Skinner,male,28.4,5,5,99241,96.64,B20,Q,10

In [13]:
import numpy as np
import pandas as pd

labels = ['a','b','c']
my_data = [10,20,30]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

print ("Labels:", labels)
print("My data:", my_data)
print(arr)
print("Dictionary:", d)


#pd.series(labels, index = my_Data)

Labels: ['a', 'b', 'c']
My data: [10, 20, 30]
[10 20 30]
Dictionary: {'a': 10, 'b': 20, 'c': 30}

In [14]:
pd.Series(my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [15]:
pd.Series(labels, index=my_data)

10    a
20    b
30    c
dtype: object

In [ ]:
print ("\nHolding numerical data\n",'-'*25, sep='')
print(pd.Series(arr)[0])

In [20]:
print ("\nHolding text labels\n",'-'*20, sep='')
print(pd.Series(labels))

Holding text labels
--------------------
0    a
1    b
2    c
dtype: object

In [34]:

d = {'a':"kjhk",'b':20,'c':30}
d.items()

pd.DataFrame(d, index = ['a','b'])

      a   b   c
a  kjhk  20  30
b  kjhk  20  30

In [51]:
print ("\nHolding objects from a dictionary\n",'-'*40, sep='')
my_series = pd.Series([10, 20, 30, 40])
print(my_series.mean())

Holding objects from a dictionary
----------------------------------------
25.0

In [37]:
ser1 = pd.Series([1,2,3,4],index = [2,4,6,8])
ser1

2    1
4    2
6    3
8    4
dtype: int64

In [52]:
ser2 = pd.Series([1,2,5,4],['CA', 'OR', 'NV', 'AZ'])
ser2

CA    1
OR    2
NV    5
AZ    4
dtype: int64

In [53]:
ser1[0:3:2]

2    1
6    3
dtype: int64

In [65]:
print ("\nIndexing by number (positional value in the series)\n",'-'*52, sep='')
print("Value for CA in ser1:", ser1[2])
print("Value for AZ in ser1:", ser1[4])
print("Value for NV in ser2:", ser2['NV'])

Indexing by number (positional value in the series)
----------------------------------------------------
Value for CA in ser1: 1
Value for AZ in ser1: 2
Value for NV in ser2: 5

In [67]:
print ("\nIndexing by a range\n",'-'*25, sep='')
print ("Value for OR, CO, and AZ in ser1:\n", ser1[0:3:2], sep='')

Indexing by a range
-------------------------
Value for OR, CO, and AZ in ser1:
2    1
6    3
dtype: int64

In [66]:
ser1 = pd.Series([1,2,3,4],['CA', 'OR', 'CO', 'CA'])
ser2 = pd.Series([1,2,5,4],['CA', 'NV', 'AZ','OR'])
ser3 = ser1+ser2
ser3

AZ    NaN
CA    2.0
CA    5.0
CO    NaN
NV    NaN
OR    6.0
dtype: float64

In [69]:
print ("\nAfter adding the two series, the result looks like this...\n",'-'*59, sep='')
print(ser3)
print("\nPython tries to add values where it finds common index name, and puts NaN where indices are missing\n")

After adding the two series, the result looks like this...
-----------------------------------------------------------
AZ    NaN
CA    2.0
CA    5.0
CO    NaN
NV    NaN
OR    6.0
dtype: float64

Python tries to add values where it finds common index name, and puts NaN where indices are missing

In [67]:
print ("\nThe idea works even for multiplication...\n",'-'*43, sep='')
print (ser1*ser2)

The idea works even for multiplication...
-------------------------------------------
AZ    NaN
CA    1.0
CA    4.0
CO    NaN
NV    NaN
OR    8.0
dtype: float64

In [109]:
from numpy.random import randn as rn
np.random.seed(101)
matrix_data = rn(5,4)
matrix_data
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']

df = pd.DataFrame(matrix_data,row_labels,column_headings)
print("\nThe data frame looks like\n",'-'*45, sep='')
df

The data frame looks like
---------------------------------------------

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [111]:
df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [115]:
df.loc['C','W']

-2.018168244037392

In [73]:
print("\nType of the pair of columns: ", type(df[['X','Z']]), sep='')
print ("\nSo, for more than one column, the object turns into a DataFrame")

Type of the pair of columns: <class 'pandas.core.frame.DataFrame'>

So, for more than one column, the object turns into a DataFrame

In [86]:
print("\nA column is created by assigning it in relation to an existing column\n",'-'*75, sep='')
df['New'] = df['X']+df['Z']
df['New (Sum of X and Z)'] = df['X']+df['Z']
print(df)

A column is created by assigning it in relation to an existing column
---------------------------------------------------------------------------
          W         X         Y         Z       New  New (Sum of X and Z)
B  0.651118 -0.319318 -0.848077  0.605965  0.286647              0.286647
D  0.188695 -0.758872 -0.933237  0.955057  0.196184              0.196184
E  0.190794  1.978757  2.605967  0.683509  2.662266              2.662266

In [87]:
df

          W         X         Y         Z       New  New (Sum of X and Z)
B  0.651118 -0.319318 -0.848077  0.605965  0.286647              0.286647
D  0.188695 -0.758872 -0.933237  0.955057  0.196184              0.196184
E  0.190794  1.978757  2.605967  0.683509  2.662266              2.662266

In [88]:
print("\nA column is dropped by using df.drop() method\n",'-'*55, sep=' ')
df.drop("A",inplace=True) # Notice the axis=1 option, axis = 0 is default, so one has to change it to 1

A column is dropped by using df.drop() method
 -------------------------------------------------------

KeyError: "['A'] not found in axis"

In [90]:
df

          W         X         Y         Z       New  New (Sum of X and Z)
B  0.651118 -0.319318 -0.848077  0.605965  0.286647              0.286647
D  0.188695 -0.758872 -0.933237  0.955057  0.196184              0.196184
E  0.190794  1.978757  2.605967  0.683509  2.662266              2.662266

In [91]:
df1=df.drop('B')
print("\nA row (index) is dropped by using df.drop() method and axis=0\n",'-'*65, sep='')
print(df1)

A row (index) is dropped by using df.drop() method and axis=0
-----------------------------------------------------------------
          W         X         Y         Z       New  New (Sum of X and Z)
D  0.188695 -0.758872 -0.933237  0.955057  0.196184              0.196184
E  0.190794  1.978757  2.605967  0.683509  2.662266              2.662266

In [92]:
print("\nAn in-place change can be done by making inplace=True in the drop method\n",'-'*75, sep='')
df.drop('New (Sum of X and Z)', axis=1, inplace=True)
print(df)

An in-place change can be done by making inplace=True in the drop method
---------------------------------------------------------------------------
          W         X         Y         Z       New
B  0.651118 -0.319318 -0.848077  0.605965  0.286647
D  0.188695 -0.758872 -0.933237  0.955057  0.196184
E  0.190794  1.978757  2.605967  0.683509  2.662266

In [89]:
print("\nLabel-based 'loc' method can be used for selecting row(s)\n",'-'*60, sep='')
print("\nSingle row\n")
print(df.iloc[3,1])

Label-based 'loc' method can be used for selecting row(s)
------------------------------------------------------------

Single row

0.5325801172519973

In [76]:
print("\nMultiple rows\n")
print(df.loc[['B','C']])

Multiple rows

          W         X         Y         Z       New  New (Sum of X and Z)
B -0.825837  0.225281 -0.275269  0.933660  1.158941              1.158941
C  1.005637  0.192200  0.350971  0.084337  0.276537              0.276537

In [84]:
print("\nIndex position based 'iloc' method can be used for selecting row(s)\n",'-'*70, sep='')
print("\nSingle row\n")
print(df.iloc[3])

Index position based 'iloc' method can be used for selecting row(s)
----------------------------------------------------------------------

Single row

W                       0.573571
X                       0.532580
Y                       0.830707
Z                      -1.710848
New                    -1.178268
New (Sum of X and Z)   -1.178268
Name: D, dtype: float64

In [55]:
print("\nMultiple rows\n")
print(df.iloc[[1,2]])

Multiple rows

          W         X         Y         Z       New
B -0.426458  1.521220  0.564656  1.270648  2.791868
D -0.379325 -0.407048 -0.183829  1.249603  0.842555

In [82]:
#### Subsetting DataFrame

In [163]:

matrix_data = rn(5,4)
row_labels = ['A','B','C','D','E']
column_headings = ['W','X','Y','Z']
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)

df

          W         X         Y         Z
A  0.379492 -0.002832 -0.077715 -0.390345
B -0.513974  0.287624  0.138252  0.119522
C  0.380819  1.334436 -0.240133 -0.474422
D  0.539507 -1.955534  1.005590  0.729170
E  1.722322 -0.181394 -0.365300 -0.771952

In [164]:
print("\nThe DatFrame\n",'-'*45, sep='')
print(df)

The DatFrame
---------------------------------------------
          W         X         Y         Z
A  0.379492 -0.002832 -0.077715 -0.390345
B -0.513974  0.287624  0.138252  0.119522
C  0.380819  1.334436 -0.240133 -0.474422
D  0.539507 -1.955534  1.005590  0.729170
E  1.722322 -0.181394 -0.365300 -0.771952

In [85]:
print("\nElement at row 'B' and column 'Y' is\n") 
print(df.loc[['B','C'],['Y','W']])

Element at row 'B' and column 'Y' is

          Y         W
B  0.682552 -0.135278
C  0.316632 -0.514722

In [86]:
print("\nSubset comprising of rows B and D, and columns W and Y, is\n")
df.iloc[[1,2,3],[0,1]]

Subset comprising of rows B and D, and columns W and Y, is

          W         X
B -0.135278  0.978669
C -0.514722  1.001019
D  0.530561 -0.508767

In [87]:
print(df.loc[['B','C'],])

          W         X         Y         Z
B -0.135278  0.978669  0.682552 -0.007968
C -0.514722  1.001019  0.316632 -2.059220

In [88]:
print("\nThe DataFrame\n",'-'*45, sep='')
print(df)

The DataFrame
---------------------------------------------
          W         X         Y         Z
A  0.507238 -0.763080  0.311180 -0.909343
B -0.135278  0.978669  0.682552 -0.007968
C -0.514722  1.001019  0.316632 -2.059220
D  0.530561 -0.508767 -0.863379  1.081514
E  0.218491  1.234449 -0.293936  0.183294

In [89]:
print("\nBoolean DataFrame(s) where we are checking if the values are greater than 0\n",'-'*75, sep='')
print(df>0)

Boolean DataFrame(s) where we are checking if the values are greater than 0
---------------------------------------------------------------------------
       W      X      Y      Z
A   True  False   True  False
B  False   True   True  False
C  False   True   True  False
D   True  False  False   True
E   True   True  False   True

In [90]:
print("\n")
print(df.loc[['A','B','C']]>0)

       W      X     Y      Z
A   True  False  True  False
B  False   True  True  False
C  False   True  True  False

In [91]:
booldf = df>0
print("\nDataFrame indexed by boolean dataframe\n",'-'*45, sep='')
print(df[booldf])

DataFrame indexed by boolean dataframe
---------------------------------------------
          W         X         Y         Z
A  0.507238       NaN  0.311180       NaN
B       NaN  0.978669  0.682552       NaN
C       NaN  1.001019  0.316632       NaN
D  0.530561       NaN       NaN  1.081514
E  0.218491  1.234449       NaN  0.183294

In [93]:
import pandas as pd 
import numpy as np
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']
matrix_data

matrix([[ 22,  66, 140],
        [ 42,  70, 148],
        [ 30,  62, 125],
        [ 35,  68, 160],
        [ 25,  62, 152]])

In [95]:
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nA new DataFrame\n",'-'*25, sep='')
print(df)

A new DataFrame
-------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [96]:
df[df['Height']>65]

   Age  Height  Weight
A   22      66     140
B   42      70     148
D   35      68     160

In [170]:
print("\nRows with Height > 65 inch\n",'-'*35, sep='')
print(df[df['Height']>65])

Rows with Height > 65 inch
-----------------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
D   35      68     160

In [171]:
df['Height']>65

A     True
B     True
C    False
D     True
E    False
Name: Height, dtype: bool

In [98]:
booldf1 = df['Height']>65
booldf2 = df['Weight']>145

In [99]:
print("\nRows with Height > 65 inch and Weight >145 lbs\n",'-'*55, sep='')
print(df[(booldf1) & (booldf2)])

Rows with Height > 65 inch and Weight >145 lbs
-------------------------------------------------------
   Age  Height  Weight
B   42      70     148
D   35      68     160

In [174]:
print("\nDataFrame with only Age and Weight columns whose Height > 65 inch\n",'-'*68, sep='')
print(df[booldf1][['Age','Weight']])

DataFrame with only Age and Weight columns whose Height > 65 inch
--------------------------------------------------------------------
   Age  Weight
A   22     140
B   42     148
D   35     160

In [175]:
matrix_data = np.matrix('22,66,140;42,70,148;30,62,125;35,68,160;25,62,152')
row_labels = ['A','B','C','D','E']
column_headings = ['Age', 'Height', 'Weight']

In [100]:
df = pd.DataFrame(data=matrix_data, index=row_labels, columns=column_headings)
print("\nThe DataFrame\n",'-'*25, sep='')
print(df)

The DataFrame
-------------------------
   Age  Height  Weight
A   22      66     140
B   42      70     148
C   30      62     125
D   35      68     160
E   25      62     152

In [177]:
print("\nAfter resetting index\n",'-'*35, sep='')
print(df.reset_index())

After resetting index
-----------------------------------
  index  Age  Height  Weight
0     A   22      66     140
1     B   42      70     148
2     C   30      62     125
3     D   35      68     160
4     E   25      62     152

In [178]:
print("\nAfter resetting index with 'drop' option TRUE\n",'-'*45, sep='')
print(df.reset_index(drop=True))
"Student Teacher Engineer Doctor Nurse".split()

After resetting index with 'drop' option TRUE
---------------------------------------------
   Age  Height  Weight
0   22      66     140
1   42      70     148
2   30      62     125
3   35      68     160
4   25      62     152

['Student', 'Teacher', 'Engineer', 'Doctor', 'Nurse']

In [101]:
print("\nAdding a new column 'Profession'\n",'-'*45, sep='')
df['Profession'] = "Student Teacher Engineer Doctor Nurse".split()
print(df)

Adding a new column 'Profession'
---------------------------------------------
   Age  Height  Weight Profession
A   22      66     140    Student
B   42      70     148    Teacher
C   30      62     125   Engineer
D   35      68     160     Doctor
E   25      62     152      Nurse

In [102]:
print("\nSetting 'Profession' column as index\n",'-'*45, sep='')
print (df.set_index('Profession'))

Setting 'Profession' column as index
---------------------------------------------
            Age  Height  Weight
Profession
Student      22      66     140
Teacher      42      70     148
Engineer     30      62     125
Doctor       35      68     160
Nurse        25      62     152

In [105]:
#multi-indexing
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [106]:
print("\nTuple pairs after the zip and list command\n",'-'*45, sep='')
print(hier_index)

Tuple pairs after the zip and list command
---------------------------------------------
[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [107]:
hier_index = pd.MultiIndex.from_tuples(hier_index)
print("\nIndex hierarchy\n",'-'*25, sep='')
print(hier_index)

Index hierarchy
-------------------------
MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [191]:
print("\nIndex hierarchy type\n",'-'*25, sep='')
print(type(hier_index))

Index hierarchy type
-------------------------
<class 'pandas.core.indexes.multi.MultiIndex'>

In [108]:
print("\nCreating DataFrame with multi-index\n",'-'*37, sep='')
#np.random.seed(101)
df1 = pd.DataFrame(data=np.round(rn(6,3)), index= hier_index, columns= ['A','B','C'])
print(df1)

Creating DataFrame with multi-index
-------------------------------------
        A    B    C
G1 1  0.0  2.0 -2.0
   2 -1.0 -0.0  0.0
   3  0.0  0.0  1.0
G2 1  0.0  1.0  0.0
   2 -0.0 -1.0 -1.0
   3  0.0 -0.0  2.0